// Example configuration for uni-app project
// Generated by 'nexus init' command

/** @type {import('../../src/types').NexusConfig} */
module.exports = {
	// Project framework type (auto-detected)
	projectType: 'uni-app',

	// Target platform
	platform: 'weapp',

	// Mini program App ID
	appId: process.env.MP_APP_ID || 'wx-your-app-id-here',

	// Path to private key file
	privateKeyPath: process.env.MP_PRIVATE_KEY_PATH || './private.key',

	// Project root path
	projectPath: '.',

	// Build output directory
	outputDir: 'dist/build/mp-weixin',

	// Additional CI options
	ciOptions: {
		// Custom settings for miniprogram-ci
		setting: {
			es6: true,
			minify: true,
			codeProtect: false, // uni-app may have compatibility issues
		},
	},

	// Optional: Notification settings
	// notify: {
	//   webhook: 'https://your-webhook-url',
	//   provider: 'feishu', // 'feishu' | 'dingtalk' | 'wechatwork'
	// },
};


