/**
 * 退出码定义
 * 遵循 Unix 标准：0 成功，非 0 失败
 */
export const ExitCodes = {
  // 成功
  SUCCESS: 0,

  // 通用错误 1-19
  ERROR_UNKNOWN: 1,
  ERROR_INVALID_ARGUMENTS: 2,
  ERROR_CONFIG_NOT_FOUND: 3,
  ERROR_CONFIG_INVALID: 4,

  // 文件系统错误 20-39
  ERROR_FILE_NOT_FOUND: 20,
  ERROR_FILE_PERMISSION: 21,
  ERROR_DIR_NOT_FOUND: 22,

  // 网络/API错误 40-59
  ERROR_NETWORK: 40,
  ERROR_API_AUTHENTICATION: 41,
  ERROR_API_RATE_LIMIT: 42,

  // 构建错误 60-79
  ERROR_BUILD_FAILED: 60,
  ERROR_BUILD_TOOL_NOT_FOUND: 61,
  ERROR_BUILD_TIMEOUT: 62,

  // 部署错误 80-99
  ERROR_DEPLOY_FAILED: 80,
  ERROR_DEPLOY_VERSION_EXISTS: 81,
  ERROR_DEPLOY_INVALID_VERSION: 82,

  // 平台特定错误 100-119
  ERROR_WEAPP_CI_FAILED: 100,
  ERROR_WEAPP_INVALID_APPID: 101,
  ERROR_WEAPP_INVALID_PRIVATE_KEY: 102,
} as const;

export type ExitCode = typeof ExitCodes[keyof typeof ExitCodes];